version: "3.7"
services:
  api:
    image: jeffrygonzalez/few100api:latest
    depends_on:
      - sql
    ports: 
      - 80:80
    environment: 
      - ConnectionStrings__library=server=sql;database=library_docker;user id=sa;password=TokyoJoe138!
  sql:
    image: jeffrygonzalez/sql-few100-jan-2021:latest
    ports:
      - 1433:1433